from enum import Enum

class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    VALIDATED = "VALIDATED"
    READY_FOR_EXTRACTION = "READY_FOR_EXTRACTION"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"

class ProcessingStage(str, Enum):
    UPLOAD = "UPLOAD"
    CLASSIFICATION = "CLASSIFICATION"
    WAITING_EXTRACTION = "WAITING_EXTRACTION"
    EXTRACTION = "EXTRACTION"
    NORMALIZATION = "NORMALIZATION"
    KNOWLEDGE_BASE = "KNOWLEDGE_BASE"
    LANGGRAPH = "LANGGRAPH"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class DocumentType(str, Enum):
    UNKNOWN = "UNKNOWN"
    PRESCRIPTION = "PRESCRIPTION"
    LAB_REPORT = "LAB_REPORT"
    RADIOLOGY_REPORT = "RADIOLOGY_REPORT"
    CLINICAL_NOTE = "CLINICAL_NOTE"
    DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY"
    OPERATIVE_NOTE = "OPERATIVE_NOTE"
    PATHOLOGY_REPORT = "PATHOLOGY_REPORT"
    REFERRAL = "REFERRAL"
    INSURANCE_FORM = "INSURANCE_FORM"
    OTHER = "OTHER"
