export const RiskLevel = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

export const EvidenceCategory = {
  DIAGNOSIS: 'DIAGNOSIS',
  DOCUMENT: 'DOCUMENT',
  CLINICAL_FINDING: 'CLINICAL_FINDING',
  IMAGING: 'IMAGING',
  MEDICATION: 'MEDICATION',
  PROVIDER_TYPE: 'PROVIDER_TYPE',
  CONSERVATIVE_TREATMENT: 'CONSERVATIVE_TREATMENT',
  LAB_RESULT: 'LAB_RESULT',
  INSURANCE: 'INSURANCE',
};

export const EvidenceStatus = {
  MATCHED: 'MATCHED',
  MISSING: 'MISSING',
  PARTIAL: 'PARTIAL',
  CONFLICTING: 'CONFLICTING',
};
